name: ci

env:
  NODE_VERSION: '14.x'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Tonkotsu
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      -
        name: Install dependencies
        run: npm install
      -
        name: Build
        run: npm run build --if-present
      -
        name: Test
        run: npm run test --if-present
