name: ci

env:
  NODE_VERSION: '14.x'
  WEBAPP_NAME: tonkotsu
  WEBAPP_PACKAGE_PATH: '.'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy-staging:
    name: Build and deploy Tonkotsu in Staging
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    environment: staging
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      -
        name: Install dependencies
        run: npm install
      -
        name: Build
        run: npm run build --if-present
      -
        name: Test
        run: npm run test --if-present
      -
        name: Test coverge
        run: npm run report-coverage
      - 
        name: Codecov
        uses: codecov/codecov-action@v1.5.0
      -
        name: Deploy to WebApp Staging
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          publish-profile: ${{ secrets.WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.WEBAPP_PACKAGE_PATH }}
          slot-name: staging
          
  build-and-deploy-production:
    name: Build and deploy Tonkotsu in Production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    environment: production
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      -
        name: Install dependencies
        run: npm install
      -
        name: Build
        run: npm run build --if-present
      -
        name: Deploy to WebApp Production
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          publish-profile: ${{ secrets.WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.WEBAPP_PACKAGE_PATH }}
          slot-name: production
      
