name: ci

env:
  NODE_VERSION: '14.x'
  WEBAPP_NAME: tonkotsu2
  WEBAPP_PACKAGE_PATH: '.'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Tonkotsu
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      -
        name: Install dependencies
        run: npm install
      -
        name: Build
        run: npm run build --if-present
      -
        name: Test
        run: npm run test --if-present
      -
        name: Test coverge
        run: npm run report-coverage
      - 
        name: Codecov
        uses: codecov/codecov-action@v1.5.0
  deploy:
    name: cd
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Deploy to WebApp Staging
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          publish-profile: ${{ secrets.WEBAPP_PUBLISH_PROFILE_STAGING }}
          package: ${{ env.WEBAPP_PACKAGE_PATH }}
          slot-name: staging
      
    
